const css = [
  {
    name: "Css magic",
    link: "https://luayabbas1981.github.io/css-magic/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/css-magic.png",
  },
  {
    name: "Css magicII",
    link: "https://luayabbas1981.github.io/css-magic2/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/css-magic2.png",
  },
  {
    name: "Css magicIII",
    link: "https://luayabbas1981.github.io/css-magicIII/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/css-magic3.png",
  },
  {
    name: "Logo",
    link: "https://luayabbas1981.github.io/logo/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/logo.png",
  },
  {
    name: "Hummingbird",
    link: "https://luayabbas1981.github.io/hummingbird/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/hummingbird.png",
  },
  {
    name: "Theatre",
    link: "https://luayabbas1981.github.io/theater/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/theatre.png",
  },

  {
    name: "Dance ",
    link: "https://luayabbas1981.github.io/dance/",
    title: "3D",
    type: "3D",
    src: "./assets/images/cssImages/dance.png",
  },
  {
    name: "Pikachu ",
    link: "https://luayabbas1981.github.io/pikachu/",
    title: "2D",
    type: "2D",
    src: "./assets/images/cssImages/pikachu.png",
  },
  {
    name: "Dragon game",
    link: "https://luayabbas1981.github.io/Dragon/",
    title: "3D animation",
    type: "3D",
    src: "./assets/images/cssImages/dragon.png",
  },
  {
    name: "Funny square",
    link: "https://luayabbas1981.github.io/funny_square/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/cube.png",
  },
  {
    name: "Logo 2 ",
    link: "https://luayabbas1981.github.io/logo-2/",
    title: "2D",
    type: "2D",
    src: "./assets/images/cssImages/logo3.png",
  },
  {
    name: "Sonic ",
    link: "https://luayabbas1981.github.io/sonic/",
    title: "3D",
    type: "3D",
    src: "./assets/images/cssImages/sonic.png",
  },
  {
    name: "Logo 3",
    link: "https://luayabbas1981.github.io/logo-3/",
    title: "2D",
    type: "2D",
    src: "./assets/images/cssImages/logo2.png",
  },
  {
    name: "Deer",
    link: "https://luayabbas1981.github.io/Deer/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/deer.png",
  },
  {
    name: "Fox",
    link: "https://luayabbas1981.github.io/Fox/",
    title: "2D",
    type: "2D",
    src: "./assets/images/cssImages/fox.png",
  },
  {
    name: "Atoms",
    link: "https://luayabbas1981.github.io/atoms/",
    title: "3D animation",
    type: "3D",
    src: "./assets/images/cssImages/atoms.png",
  },
  {
    name: "Antarctic",
    link: "https://luayabbas1981.github.io/antarctic/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/ping.png",
  },
  {
    name: "E under lamp",
    link: "https://luayabbas1981.github.io/Electrons-under-lamp/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/elec.png",
  },
  {
    name: "Bird",
    link: "https://luayabbas1981.github.io/bird/",
    title: "2D clip-path",
    type: "2D",
    src: "./assets/images/cssImages/bird.png",
  },
  {
    name: "Slack",
    link: "https://luayabbas1981.github.io/Slack/",
    title: "grid",
    src: "./assets/images/cssImages/slack.png",
  },

  {
    name: "Ubuntu",
    link: "https://luayabbas1981.github.io/ubuntu/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/ubuntu.png",
  },
  {
    name: "Sauer",
    link: "https://luayabbas1981.github.io/Sauer/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/angry.png",
  },
  {
    name: "Wanduhr",
    link: "https://luayabbas1981.github.io/Wanduhr/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/clock.png",
  },
  {
    name: "Ramadan",
    link: "https://luayabbas1981.github.io/Ramadan/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/ramadan.png",
  },
  {
    name: "Golden cube",
    link: "https://luayabbas1981.github.io/Golden-cube/",
    title: "3D animation",
    type: "3D",
    src: "./assets/images/cssImages/cube3.png",
  },
  {
    name: "React",
    link: "https://luayabbas1981.github.io/React/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/react.png",
  },
  {
    name: "Icons Challenge",
    link: "https://luayabbas1981.github.io/Font-Awesome-Challenge/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/challenge.png",
  },
  {
    name: "Icons war",
    link: "https://luayabbas1981.github.io/Font-Awesome-gangster-war/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/war.png",
  },
  {
    name: "Icons war 2",
    link: "https://luayabbas1981.github.io/Font-Awesome-gangster-war-2/",
    title: "2D animation",
    type: "2D",
    src: "./assets/images/cssImages/war2.png",
  },
];

const dom = [
  {
    name: "Vision",
    link: "https://luayabbas1981.github.io/dream/",
    title: "web-site",
    src: "./assets/images/domImages/dream.png",
  },
  {
    name: "Moods",
    link: "https://luay-abbas.itch.io/moods",
    title: "art",
    src: "./assets/images/domImages/moods.png",
  },
  {
    name: "Rolling Calculator",
    link: "https://luayabbas1981.github.io/Rolling-Calculator/",
    title: "art",
    src: "./assets/images/domImages/rolling-calculator.png",
  },
  {
    name: "Think&Link",
    link: "https://luayabbas1981.github.io/Think-and-Link/",
    title: "art",
    src: "./assets/images/domImages/Think&Link.png",
  },
  {
    name: "Think&LinkIII",
    link: "https://luayabbas1981.github.io/Think-and-Link-III/",
    title: "art",
    src: "./assets/images/domImages/Think&Link3.png",
  },
  {
    name: "English calligraphy",
    link: "https://luayabbas1981.github.io/english-calligraphy/",
    title: "art",
    src: "./assets/images/domImages/english-calligraphy.png",
  },
  {
    name: "Arabic calligraphy",
    link: "https://luayabbas1981.github.io/arabic-calligraphy/",
    title: "art",
    src: "./assets/images/domImages/arabic-calligraphy.png",
  },
  {
    name: "Arrows",
    link: "https://luayabbas1981.github.io/arrows/",
    title: "javascript game",
    src: "./assets/images/domImages/arrows.png",
  },
  {
    name: "Unlock",
    link: "https://luayabbas1981.github.io/unlock/",
    title: "javascript game",
    src: "./assets/images/domImages/unlock.png",
  },
  {
    name: "River puzzle",
    link: "https://luayabbas1981.github.io/river-puzzle/",
    title: "javascript game",
    src: "./assets/images/domImages/river-puzzle.png",
  },
  {
    name: "Frogs",
    link: "https://luayabbas1981.github.io/frogs/",
    title: "javascript game",
    src: "./assets/images/domImages/frogs.png",
  },
  {
    name: "3D slider",
    link: "https://luayabbas1981.github.io/3D-slider/",
    title: "javascript app",
    src: "./assets/images/domImages/3D-slider.png",
  },
  {
    name: "Map slider",
    link: "https://luayabbas1981.github.io/map-slider/",
    title: "javascript app",
    src: "./assets/images/domImages/map-slider.png",
  },
  {
    name: "Clever buyer",
    link: "https://luayabbas1981.github.io/clever-buyer/",
    title: "javascript game",
    src: "./assets/images/domImages/clever-boy.png",
  },

  {
    name: "Missing part",
    link: "https://luayabbas1981.github.io/missing-part/",
    title: "javascript app",
    src: "./assets/images/domImages/missing-part.png",
  },
  {
    name: "Pickup num",
    link: "https://luayabbas1981.github.io/pick-right-numbers/",
    title: "javascript game",
    src: "./assets/images/domImages/pick-num.png",
  },
  {
    name: "Rounded name",
    link: "https://luayabbas1981.github.io/rounded-name/",
    title: "javascript app",
    src: "./assets/images/domImages/rounded name.png",
  },
  {
    name: "C-rose App",
    link: "https://luayabbas1981.github.io/colorful-rose/",
    title: "javascript app",
    src: "./assets/images/domImages/c-rose.png",
  },
  {
    name: "Focus",
    link: "https://luayabbas1981.github.io/focus/",
    title: "javascript game",
    src: "./assets/images/domImages/focus.png",
  },
  {
    name: "Focus2",
    link: "https://luayabbas1981.github.io/focus2/",
    title: "javascript game",
    src: "./assets/images/domImages/focus2.png",
  },
  {
    name: "Focus3",
    link: "https://luayabbas1981.github.io/focus3/",
    title: "javascript game",
    src: "./assets/images/domImages/focus3.png",
  },
  {
    name: "Focus4",
    link: "https://luayabbas1981.github.io/focus4/",
    title: "javascript game",
    src: "./assets/images/domImages/focus4.png",
  },
  {
    name: "Focus5",
    link: "https://luayabbas1981.github.io/focus5/",
    title: "javascript game",
    src: "./assets/images/domImages/focus5.png",
  },

  {
    name: "SSP",
    link: "https://luayabbas1981.github.io/ssp/",
    title: "javascript game",
    src: "./assets/images/domImages/ssp.png",
  },
  {
    name: "Google dic",
    link: "https://luayabbas1981.github.io/google-dic/",
    title: "javascript - API",
    src: "./assets/images/domImages/dic.png",
  },
  {
    name: "Memory game",
    link: "https://luayabbas1981.github.io/memory-game/",
    title: "javascript game",
    src: "./assets/images/domImages/memory.png",
  },
  {
    name: "Falling fruits",
    link: "https://luayabbas1981.github.io/falling-fruits/",
    title: "javascript game",
    src: "./assets/images/domImages/fruits.png",
  },
  {
    name: "Snake and ladder",
    link: "https://luayabbas1981.github.io/Snake-Ladder/",
    title: "javascript game",
    src: "./assets/images/domImages/snake.png",
  },
];

const spa = [
  {
    name: "Mack up shop Vue3",
    link: "https://aura-one-gold.vercel.app/",
    title: "Vue3 - API",
    src: "./assets/images/reactImages/Aura.png",
  },
  {
    name: "Mack up shop",
    link: "https://luayabbas1981.github.io/react-makeup-shop/",
    title: "React - API",
    src: "./assets/images/reactImages/make-up.png",
  },
  {
    name: "React calc",
    link: "https://luayabbas1981.github.io/react-calc/",
    title: "React - useReduce",
    src: "./assets/images/reactImages/calc.png",
  },
  {
    name: "todo app",
    link: "https://luayabbas1981.github.io/react-todo/",
    src: "./assets/images/reactImages/todo.png",
  },
  {
    name: "My cats",
    link: "https://luayabbas1981.github.io/react-cats/",
    src: "./assets/images/reactImages/cats.png",
  },
  {
    name: "Software definitions",
    link: "https://github.com/Luayabbas1981/programmierdefinitionen#programmierdefinitionen",
    title: "markdown",
    src: "./assets/images/reactImages/softwares.png",
  },
];

const canvas = [
  {
    name: "Magic Text",
    link: "https://luayabbas1981.github.io/magic-text/",
    title: "canvas",
    src: "./assets/images/canvasImages/magic-text.png",
  },
  {
    name: "Fisherman",
    link: "https://luayabbas1981.github.io/fishman/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/fisherman.png",
  },
  {
    name: "Frogs2",
    link: "https://luayabbas1981.github.io/frogs2/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/frogs2.png",
  },
  {
    name: "Masha & cackes",
    link: "https://luayabbas1981.github.io/masha-and-cakes/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/masha.png",
  },
  {
    name: "Rainy image",
    link: "https://luayabbas1981.github.io/rainy-image/",
    title: "canvas",
    src: "./assets/images/canvasImages/rainy-image.png",
  },
  {
    name: "Chaos",
    link: "https://luayabbas1981.github.io/chaos/",
    title: "canvas",
    src: "./assets/images/canvasImages/chaos.png",
  },
  {
    name: "Turtle challenge",
    link: "https://luayabbas1981.github.io/race/",
    title: "canvas",
    src: "./assets/images/canvasImages/turtle.png",
  },
  {
    name: "Stars war",
    link: "https://luayabbas1981.github.io/atari/",
    title: "canvas",
    src: "./assets/images/canvasImages/atari.png",
  },
  {
    name: "Bouncy ball",
    link: "https://luayabbas1981.github.io/bouncy-ball/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/colorfulball.png",
  },
  {
    name: "Daring ball",
    link: "https://luayabbas1981.github.io/daring-ball/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/daring-ball.png",
  },
  {
    name: "UBOOT",
    link: "https://luayabbas1981.github.io/u-boot/",
    title: "canvas-game",
    src: "./assets/images/canvasImages/u-boot.png",
  },
];

const npm = [
  {
    name: "Magic Text",
    link: "https://github.com/Luayabbas1981/magic-canvas-text",
    title: "npm-library",
    src: "./assets/images/librariesImages/magic-text.png",
  },
  {
    name: "3D slider",
    link: "https://luayabbas1981.github.io/3d-slider-demo/",
    title: "npm-library-demo",
    src: "./assets/images/librariesImages/3d-slider.png",
  },
  {
    name: "Remote CSS Injector",
    link: "https://github.com/Luayabbas1981/remote-css-injector-v2",
    title: "github repo",
    src: "./assets/images/librariesImages/remote-control.webp",
  },
  {
    name: "Sheets slider",
    link: "https://luayabbas1981.github.io/sheets-slider-demo/",
    title: "npm-library-demo",
    src: "./assets/images/librariesImages/sheets-slider.png",
  },

  {
    name: "Animate slider",
    link: "https://luayabbas1981.github.io/virtual-slider/",
    title: "npm-library-demo",
    src: "./assets/images/librariesImages/animate-slider.png",
  },
  {
    name: "FF",
    link: "https://github.com/Luayabbas1981/FF",
    title: "npm-library-demo",
    src: "./assets/images/librariesImages/pfs.png",
  },
];

export { css, dom, spa, canvas, npm };
